# Generated by Django 3.1.1 on 2020-09-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('days', models.PositiveIntegerField(default=10)),
                ('pay', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('accepted_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
